# Generated by Django 5.0.4 on 2024-04-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_group', models.CharField(max_length=255)),
                ('unit_of_measurement', models.CharField(choices=[('Meter', 'Meter'), ('Kilogram', 'Kilogram'), ('Liter', 'Liter'), ('Piece', 'Piece')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_without_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=255)),
                ('storage_location', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='photos/')),
            ],
        ),
    ]
