# Generated by Django 5.0.4 on 2024-04-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_alter_item_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(blank=True, upload_to='web_app/photos/'),
        ),
    ]
