# Generated by Django 5.0.4 on 2024-04-07 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0004_alter_item_photo'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='web_app_item',
        ),
    ]
