# Generated by Django 5.0.4 on 2024-04-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0006_request'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='web_app_tma_requests',
        ),
    ]
