# Generated by Django 5.0.4 on 2024-04-08 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0008_alter_request_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='request',
            table='web_app_requests',
        ),
    ]
